language: python
python:
    - "3.4"
    - "3.5"
    - "cython"
install:
    - "pip install -r requirements.txt"
    - "pip install -r requirements-dev.txt"
script:
    - "make test"
notifications:
    email:
        recipients:
            - "ellisonleao@gmail.com"
            - "sudowilliam@gmail.com"
